name: Issue Dataset to Pull Request

on:
  issues:
    types: [opened]

jobs:
  run-script:
    if: contains(github.event.issue.labels.*.name, 'new_dataset')
    runs-on: ubuntu-latest

    steps:
    - name: "[LOG] Issue notification of start of processing"
      uses: actions/github-script@v7.0.1
      with:
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: 'Your request is being processed...'
          })
              
    - name: "[TASK] Clone the repository into the GitHub Actions"
      uses: actions/checkout@v4.2.2

    - name: "[TASK] Set up Python"
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.12.1'

    - name: "[TASK] Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/issue_dataset_to_pr/requirements.txt
        pip install -r scripts/csv_to_markdown/requirements.txt

    - name: "[TASK] Run the Python script"
      run: |
        python .github/workflows/issue_dataset_to_pr/main.py 2>error.log
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        PYTHONPATH: ${{ github.workspace }}
    
    - name: "[LOG] Comment on Issue if Error"
      if: ${{ failure() }}
      uses: actions/github-script@v7.0.1
      with:
        script: |
          const fs = require('fs');
          const errorLog = fs.readFileSync('error.log', 'utf8');
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `An error occurred while processing the issue:\n\n\`\`\`\n${errorLog}\`\`\``
          });

